### PR TITLE
Rotation instructions

### PR DESCRIPTION
**Pull request by r4vi**
Adds a Rotation.org (org-mode) file which describes all the credentials and a
priority for the order in which they should be rotated.

It also adds a generated Rotation.html file which is easier for non-emacs users
to read.

To review, check this branch out and open `Rotation.html` in your browser.

### CODE REVIEW

**Comment by r4vi** [comment]
@davidread added a link to the logstash / elk wiki page

**Comment by xoen** [comment]
I didn't started to have a look at this yet - so apologies if instructions are in the encrypted file - but how do you generate the HTML one? is this `Rotation.org` file a standard file thing? (like `robots.txt` or something?)

**Comment by xoen** [comment]
Can't find much in the `.org` file on how to generate the HTML, maybe add a note in the README or something ☺️ ?

**Comment by r4vi** [comment]
@xoen No, Rotation.org is an `org-mode` file - emacs thing that can then export to html/pdf/latex/slideshow so I exported it to `html`

**Comment by r4vi** [comment]
> Can't find much in the `.org` file on how to generate the HTML, maybe add a note in the README or something  ?

I don't expect anyone else to ever export it but I didn't want to leave the .org file out since it already exists.

**Pull request merged**
