### PR TITLE
Update lookup user AWS credentials

### PR DESCRIPTION
**Pull request by calumabarnett**
The credentials for the AWS user for Concourse lookup pipelines are out of date causing some job runs to fail. This PR updates the access key ID and secret access key.

### CODE REVIEW

**Comment by calumabarnett** [comment]
FYI @Danjiv

**Review by neillturner — COMMENTED** [review]
is there a reason this shows as an empty file. I assume you have updated the aws keys in the file and encrypted it with git encrypt?

**Comment by calumabarnett** [comment]
@neillturner yep, it comes up as a binary file due to encryption with git-crypt. You should be able to view the changes if you clone and unlock.

All I've done is update one of the AWS keys.

**Review by neillturner — APPROVED** [review]
assume keys are updated ok

**Pull request merged**
