### PR TITLE
Nginx-Ingress: Don't trust client x-forwarded-for header

### PR DESCRIPTION
**Pull request by r4vi**
This feature has been disabled by default in newer versions of this chart but
upgrading is a more involved process. For now I'm turning the
`use-forwarded-headers` option off manually in the configmap

To redeploy without upgrading the chart use the following command:

`helm upgrade cluster-ingress stable/nginx-ingress --version=0.29.1 -f
chart-env-config/alpha/nginx-ingress.yml --debug --dry-run`

If the output looks OK then re-run but remove `--dry-run`.

### CODE REVIEW

**Comment by r4vi** [comment]
use-forwarded-headers: "false" is default in v0.22.0 of nginx-ingress: https://github.com/kubernetes/ingress-nginx/blob/master/Changelog.md#0220

**Comment by r4vi** [comment]
@xoen @djsd123 I'll roll this out tonight

**Comment by xoen** [comment]
I would have probably upgraded it in daylight but as you pointed out, websocket connections would be effected and we don't know how that would be handled by some of the applications - they may require the user to refresh the page - not a massive deal but probably wiser to do it later as you said 👍 .

**Comment by r4vi** [comment]
deployed on `alpha`

**Pull request merged**
