### PR TITLE
AlertManager-APIServerLatencyHigh

### PR DESCRIPTION
**Pull request by djsd123**
To stop alerts of __action:__ `LIST` in __namespace:__ `default` when
the k8s apiserver takes long to respond.

### CODE REVIEW

**Comment by r4vi** [comment]
do we have too many pods in default? :thinking:

**Comment by djsd123** [comment]
Hmmm, yes you're right but I am seeing this..

```
      - match:
           alertname: APIServerLatencyHigh
           namespace: 'default'
           verb: 'LIST'
        receiver: 'null'

```

I'll re-push.

**Comment by djsd123** [comment]
Something weird happened.  Had to fix an empty conflict???  In any case, re-pushed.

**Comment by r4vi** [comment]
looks good

**Pull request merged**
