### PR TITLE
kube-dashboard config: Updated list of users allowed to access

### PR DESCRIPTION
**Pull request by xoen**
Updated list of users having access to Kube Dashboard.

### CODE REVIEW

**Comment by xoen** [comment]
@kerin I completely forgot about this one. Basically I updated the RE that determine the users having access to Kube Dashboard.

**Comment by xoen** [comment]
(rebased off master)

**Comment by xoen** [comment]
FYI @kerin these are actually Google Apps usernames (the bit before @digital...).

**Comment by xoen** [comment]
I don't touch this in ages but as far as I can remember we use Google App authentication for the k8s dashboard.

**Comment by kerin** [comment]
@xoen oh sorry, you're right - the couple of users we want to add do actually have Digital email addresses too though, if you can provide those @RobinL ? (probably best to provide them via another channel than public Github)

**Comment by xoen** [comment]
Closing this as we don't have a proxy in front of kube-dashboard anymore.

(as discussed this offline with @djsd123)

**Pull request closed without merging**
