### PR TITLE
Cluster Stability: Image Pre Puller

### PR DESCRIPTION
**Pull request by djsd123**
[Trello](https://trello.com/c/qPjANZwm)

Reduce the number of images pulled on node initialisation

### CODE REVIEW

**Comment by r4vi** [comment]
@xoen I'd be tempted to keep the latest "old" version of rstudio because there are a lot of people still on that

**Comment by xoen** [comment]
Good point Ravi 👍 

looks like helm chart version with `1.1.463+conda, R: 3.5.1, Python: 3.7 patch: 1` description is very popular. I think it may be `e: `rstudio:r3.5.1-py3.7-conda-1` (there is also one without the `-1` don't know if there is an easy-ish way to get stats on popular images) - but worth double checking maybe.

**Comment by r4vi** [comment]
@xoen I think popular images can be seen here: https://grafana.services.alpha.mojanalytics.xyz/d/E8DvK68mk/image-audit?orgId=1

**Comment by xoen** [comment]
oh yeah I forgot, nice ☺️

**Comment by xoen** [comment]
image

basically `r3.5.1-py3.7-conda-1` is relatively popular so worth adding it back until it stops being popular.

**Comment by djsd123** [comment]
@xoen, I added `r3.5.1-py3.7-conda-1` back.  Thanks all

**Pull request merged**
