### PR TITLE
Add secure cookie key values for Rstudio

### PR DESCRIPTION
**Pull request by andyhd**

### CODE REVIEW

**Comment by xoen** [comment]
Had a quick look and looks fine. Shouldn't we start to use the dev Auth0 account instead of Kerin's "personal" one? But otherwise looks 👍

**Comment by andyhd** [comment]
Yes we should!

**Comment by kerin** [comment]
What we really need to do is ditch the charts and configured dirs in the main repo and move over to the new repo completely - I've made some chart changes in the main repo today, so charts are already out of sync across the two repos.

**Comment by xoen** [comment]
@kerin I feel your pain. I also [added a `chart-env-config/TEMPLATE/` directory](https://github.com/ministryofjustice/analytics-platform-ops/pull/92) in the `-ops` repo as part of the work to improve/automate environment creation.

**Comment by xoen** [comment]
Also, speaking of things out of sync, I noticed that there are few config files for helm charts not documented in the `README.md`. So it's not 100% clear whether these helm charts still need to be installed/why or not.

For example, do we still need to install`elasticsearch-curator` and `kibana`? some are probably needed, e.g. `jenkins-ci` and `kube2iam`.

Just to be clear, this is just a note, not a problem with this repo/changes itself :)

**Pull request merged**
