### PR TITLE
Kube-Prometheus: Add Image Audit Dashboard

### PR DESCRIPTION
**Pull request by r4vi**
This adds a new dashboard to grafana that tells us what jupyter and rstudio
images our users are on.

This is important to know as we move to a software catalogue model where they
can choose their own image versions

### CODE REVIEW

**Comment by xoen** [comment]
[JSON Bourne](https://www.reddit.com/r/ProgrammerHumor/comments/6yf7bx/json_bourne/)...let me have a look to see if I can understand that and/or spot anything wrong 👍

**Comment by xoen** [comment]
I'll have a read at some Grafana/Prometheus/Aliens documentation and see if I can understand this.

Otherwise, it may be best if we just sit together and you run me through this.

**Comment by xoen** [comment]
Tried a couple of times and still no data is displayed 🤷‍♂️

**Comment by r4vi** [comment]
@xoen seeing the same, I'll see if the same metric is exposed for deployments

**Comment by r4vi** [comment]
doesn't look like you can get image from deployment: https://github.com/kubernetes/kube-state-metrics/blob/master/Documentation/deployment-metrics.md

**Pull request merged**
